//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KArina_Fitness
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fitness_kpEntities : DbContext
    {
        public fitness_kpEntities()
            : base("name=fitness_kpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OrderKarina> OrderKarina { get; set; }
        public virtual DbSet<ServiceKarina> ServiceKarina { get; set; }
        public virtual DbSet<UserKarina> UserKarina { get; set; }
    }
}
