//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KArina_Fitness
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceKarina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceKarina()
        {
            this.OrderKarina = new HashSet<OrderKarina>();
        }
    
        public string Title { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> Count { get; set; }
        public int Id { get; set; }
        public string photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderKarina> OrderKarina { get; set; }
    }
}
